# -*- coding: utf-8 -*-
"""Write prototype/manifest.json from the same tables the board draws from.

Generated, never hand-kept: the ids come out of data.js and the file list comes
off disk, so the manifest cannot describe an asset that is not there or miss one
that is. Every path is a PATH — nothing in this bundle is base64.
"""
import json, pathlib
HERE = pathlib.Path(__file__).resolve().parent.parent
ROOT = HERE.parent.parent
MK = ROOT / "assets" / "mk"
REL = "assets/mk"                       # relative to the app's own index.html

src = (ROOT / "data.js").read_text(encoding="utf-8")
D = json.loads(src[src.index("{"):src.index("const AVATARS")].rstrip().rstrip(";").rstrip())

PORTRAITS = ("ben_gvir", "netanyahu", "deri", "lapid", "gantz", "michaeli")
TOPIC_ICONS = {"internal_sec": "internal_sec_main"}
ISSUE_ART = {"s1": ("internal_sec_s1", 300, 180),
             "s2": ("internal_sec_s2", 116, 210)}

def need(name):
    p = MK / name
    assert p.exists(), "manifest names a file that is not on disk: " + name
    return "%s/%s" % (REL, name)

man = {
    "_": ("Generated by tools/make_manifest.py. Ids are data.js's own. "
          "Sizes are the pixel size each file is written at: pick the entry that "
          "matches the size you are rendering at and never let the browser "
          "downscale a file more than 1.2x."),
    "portrait_aspect": "3:4 — 400x533 and 128x171",
    "portrait_crop_rule": {
        "face_width_pct_of_frame": 68.3,
        "crown_pct_from_top": 2.4,
        "anchor": "crown",
        "note": ("Top-anchored in the card at --mk-port-top. The bottom is the "
                 "variable edge: a long figure clips at the jacket, never at the head."),
    },
    "politicians": {},
    "topics": {},
    "issues": {},
    "props": {
        "chair": {"300": need("knesset_chair_300.webp"), "128": need("knesset_chair_128.webp"),
                  "aspect": round(300 / 350, 4)},
        "building": {"390": need("knesset_building_390.webp")},
    },
}

for pid in PORTRAITS:
    assert pid in D["politicians"], pid
    man["politicians"][pid] = {
        "name": D["politicians"][pid]["name"],
        "party": D["politicians"][pid].get("party", ""),
        "400": need("mk_%s_400.webp" % pid),
        "128": need("mk_%s_128.webp" % pid),
    }
missing = [p for p in D["politicians"] if p not in PORTRAITS]
man["politicians_without_art"] = sorted(missing)
man["fallback"] = {
    "kind": "initials-badge",
    "rule": ("First letter of each part of the shipped name, joined with a gershayim, "
             "set on the set's own eyeline at 37.7% of the box. NEVER substitute "
             "another politician's portrait."),
}

for tid, stem in TOPIC_ICONS.items():
    assert any(t["id"] == tid for t in D["topics"]), tid
    man["topics"][tid] = {k: need("%s_%d.webp" % (stem, k)) for k in (40, 52, 64, 128)}
    man["topics"][tid]["aspect"] = round(812 / 1294, 4)
    man["topics"][tid]["reads_down_to"] = 64
for t in D["topics"]:
    if t["id"] not in man["topics"]:
        man["topics"][t["id"]] = {"glyph": t["icon"]}

for iid, (stem, w, h) in ISSUE_ART.items():
    assert any(i["id"] == iid for i in D["issues"]), iid
    man["issues"][iid] = {"file": need("%s_%d.webp" % (stem, max(w, h))),
                          "w": w, "h": h}

out = HERE / "prototype" / "manifest.json"
out.write_text(json.dumps(man, ensure_ascii=False, indent=2), encoding="utf-8")
print("wrote %s — %d politicians with art, %d without, %d topic icons, %d issue graphics"
      % (out.relative_to(HERE), len(man["politicians"]),
         len(man["politicians_without_art"]),
         sum(1 for v in man["topics"].values() if "glyph" not in v),
         len(man["issues"])))
